### ISSUE TITLE
simplify dependencies

### ISSUE THREAD

**Issue by leandro-gomez** [gobstones/JSGobstones#1]
in compile.py:232 the following call is made:

```
os.system("sudo gem install sass")
```

This is a problem when you use rvm and gemsets(as I do) and I'm not sure this is the better solution.
I think this is why im getting an error when running "./compile.py --main  ./src/RawGobstones.ts"

```
/usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find sass (>= 0) amongst [minitest-5.4.3, power_assert-0.2.2, test-unit-3.0.8] (Gem::LoadError)
from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
from /usr/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
from /usr/local/bin/sass:22:in `<main>'
```

Remove this "sudo" part and considere use [bundler](https://github.com/bundler/bundler) and specify gems and ruby versions.

Also, you are using npm, bower and ruby, could all this be made just with npm?

**Comment by arypbatista** [comment]
Yes, I will simplify the build process to have only gulp tasks.
